### PR TITLE
Controllers specs

### PR DESCRIPTION
**Pull request by duskotmane**
# Features ⭐ ⭐ ⭐ 

- [ ] Add RSpec as a gem to your project.
- [ ] Create a Request spec file for all your controllers.
- [ ] Make sure that for each action the
    - response status was correct.
    - correct template was rendered.
    - response body includes correct placeholder text.

### CODE REVIEW

**Review by jerryowusu — CHANGES_REQUESTED** [review]
Hi @otmaneechchafyky 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

so-close


## Highlights
Neat code :+1: 
Used gitflow :+1: 

## Required Changes ♻️

- [x] In the `..._create_posts.rb` of the migration file, there seems to be a duplicate error (PG::DuplicateTable: ERROR) which makes it difficult to create table and migrate data in the database. Kindly fix this for a smooth running of your app.

Screenshot from 2023-09-01 09-28-57


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by duskotmane** [comment]
@jerryowusu The app is running correctly in my machine, I do not know how did you got that error?
It would be great if you checked the specs to let me know if there is something I did wrong as the task required.

showhim

**Comment by jerryowusu** [comment]
> @jerryowusu The app is running correctly in my machine, I do not know how did you got that error? It would be great if you checked the specs to let me know if there is something I did wrong as the task required.
> 
> showhim

Sorry for the late reply. This can happen when you make the corrections during setting up the database but fails to push the corrected changes to github. You can consider using a different machine to check if you will find the error. I tried using two different computers (windows and linux) and got the same error.

**Comment by Munsa1** [comment]
> > @jerryowusu The app is running correctly in my machine, I do not know how did you got that error? It would be great if you checked the specs to let me know if there is something I did wrong as the task required.
> > showhim
> 
> Sorry for the late reply. This can happen when you make the corrections during setting up the database but fails to push the corrected changes to github. You can consider using a different machine to check if you will find the error. I tried using two different computers (windows and linux) and got the same error.

Hi @jerryowusu  I have the project here for review, and I also do not have the error, it works fine

image

**Review by abdulhamiid — APPROVED** [review]
# :green_circle:  Approved! :partying_face:
Hi @otmaneechchafyky  👋, 
image
Your project is complete!  There is nothing else to say other than... It's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Write tests for controllers.

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by duskotmane** [comment]
Thank you @abdulhamiid 
@jerryowusu I will try to fix that issue, Thank you.

**Comment by otmaneechchafyky** [comment]
thank you guys @jerryowusu @abdulhamiid

**Pull request merged**
